title: CRYPTO
description: Arda's IDE offering
social_link: twitter
social_username: dogpoolsan
github_repo: dogpool/tinycoins321test
github_username: dogpool
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /tinycoins321test
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
